# MLB Scoreboard Configuration
# Place this file in the root directory of your CircuitPython device

# ===== WIFI SETTINGS =====
# Fill in your WiFi credentials
CIRCUITPY_WIFI_SSID = "Your_WiFi_Name"
CIRCUITPY_WIFI_PASSWORD = "Your_WiFi_Password"
TIMEZONE = "America/New_York"  # Standard timezone format

# ===== DISPLAY SETTINGS =====
DISPLAY_WIDTH = 64      # Matrix width in pixels
DISPLAY_HEIGHT = 32     # Matrix height in pixels
DISPLAY_BIT_DEPTH = 4   # Color bit depth
BRIGHTNESS = 0.6        # Display brightness (0.0-1.0)

# ===== MLB SETTINGS =====
FAVORITE_TEAM = "ATL"   # Atlanta Braves
TEAM_ID = 15            # Braves team ID for ESPN API
DISPLAY_MODE = "GAME_DAY"  # GAME_DAY or OFF_DAY
DATA_REFRESH_INTERVAL = 60  # Seconds between API refreshes

# ===== DEBUG SETTINGS =====
DEBUG = false           # Enable debug logging
SHOW_COORDINATES = false  # Show pixel coordinates
REPORT_MEMORY = true     # Report memory usage
